Revert "add support for opendataplane"
doesn't build for qemuarm

| arm-oe-linux-gnueabi-libtool: compile:  arm-oe-linux-gnueabi-gcc -march=armv5te -marm -mthumb-interwork
--sysroot=/home/jenkins/oe/world/shr-core/tmp-eglibc/sysroots/qemuarm -DHAVE_CONFIG_H -I. -pthread -DODP_DEBUG_PRINT=1 -W -Wall -Werror -Wstrict-prototypes
-Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-align -Wnested-externs -Wcast-qual -Wformat-nonliteral
-Wformat-security -Wundef -Wwrite-strings
-I/home/jenkins/oe/world/shr-core/tmp-eglibc/work/armv5te-oe-linux-gnueabi/opendataplane/0.2+gitAUTOINC+68a45b11e5-r0/git/platform/linux-generic/include
-I/home/jenkins/oe/world/shr-core/tmp-eglibc/work/armv5te-oe-linux-gnueabi/opendataplane/0.2+gitAUTOINC+68a45b11e5-r0/git/platform/linux-generic/include/api
-I/home/jenkins/oe/world/shr-core/tmp-eglibc/work/armv5te-oe-linux-gnueabi/opendataplane/0.2+gitAUTOINC+68a45b11e5-r0/git/include -O2 -pipe -g
-feliminate-unused-debug-types -c
/home/jenkins/oe/world/shr-core/tmp-eglibc/work/armv5te-oe-linux-gnueabi/opendataplane/0.2+gitAUTOINC+68a45b11e5-r0/git/platform/linux-generic/odp_packet.c -o
odp_packet.o
| {standard input}: Assembler messages:
| {standard input}:40: Error: selected processor does not support ARM mode `dmb st'
| {standard input}:72: Error: selected processor does not support ARM mode `dmb st'
| make[2]: *** [odp_barrier.lo] Error 1
| make[2]: *** Waiting for unfinished jobs....
| make[2]: Leaving directory
`/home/jenkins/oe/world/shr-core/tmp-eglibc/work/armv5te-oe-linux-gnueabi/opendataplane/0.2+gitAUTOINC+68a45b11e5-r0/build/platform/linux-generic'
| make[1]: *** [all-recursive] Error 1
| make[1]: Leaving directory
`/home/jenkins/oe/world/shr-core/tmp-eglibc/work/armv5te-oe-linux-gnueabi/opendataplane/0.2+gitAUTOINC+68a45b11e5-r0/build/platform'
| make: *** [all-recursive] Error 1
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at
/home/jenkins/oe/world/shr-core/tmp-eglibc/work/armv5te-oe-linux-gnueabi/opendataplane/0.2+gitAUTOINC+68a45b11e5-r0/temp/log.do_compile.12211)
NOTE: recipe opendataplane-0.2+gitAUTOINC+68a45b11e5-r0: task do_compile: Failed
ERROR: Task 12545 (/home/jenkins/oe/world/shr-core/meta-openembedded/meta-networking/recipes-support/opendataplane/opendataplane_git.bb, do_compile) failed
with exit code '1'

This reverts commit e30d6d13f8108a1e3b9bcd8e39b87526e1097f06.